NAME="ouros-auth-service"
PROVIDER_ID="ouros-auth-service"
AUTH_SERVICE_URL="http://mock-auth-service:8081"
SERVICE_CLIENT_ID="ci-user-storage"
TOKEN_URL="http://127.0.0.1:8080/realms/ouros/protocol/openid-connect/token"
PRIORITY="0"
CACHE_POLICY="NO_CACHE"
