CLIENT_TYPE="microservice"
CLIENT_ID="ci-phase3-ms-mcp-server-ouros-knowledge"
AUDIENCE="ms-mcp-server-ouros-knowledge"
SCOPE_NAME="ci-phase3-ms-mcp-server-ouros-knowledge-audience"
MAPPER_NAME="ci-phase3-ms-mcp-server-ouros-knowledge-audience"
