CLIENT_TYPE="microservice"
CLIENT_ID="ms-mcp-server-ouros-knowledge-codemode"
AUDIENCE="ms-mcp-server-ouros-knowledge-codemode"
SCOPE_NAME="ms-mcp-server-ouros-knowledge-codemode-audience"
MAPPER_NAME="ms-mcp-server-ouros-knowledge-codemode-audience"
