NAME="ouros-auth-service"
PROVIDER_ID="ouros-auth-service"
AUTH_SERVICE_URL="https://ms-auth-service.discloud.app"
SERVICE_CLIENT_ID="keycloak-user-storage"
TOKEN_URL="http://127.0.0.1:8080/realms/ouros/protocol/openid-connect/token"
PRIORITY="0"
CACHE_POLICY="NO_CACHE"
